// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Packages_service.Data.DbConfig;

#nullable disable

namespace Packages_service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240822235234_ClassesPackagesEOwner")]
    partial class ClassesPackagesEOwner
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Packages_service.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidenceID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ResidenceID");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("Packages_service.Models.Packages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Finish")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Receiver")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidenceID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Shipper")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResidenceID");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("Packages_service.Models.Residence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Complement")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Residences");
                });

            modelBuilder.Entity("Packages_service.Models.Owner", b =>
                {
                    b.HasOne("Packages_service.Models.Residence", "Residence")
                        .WithMany("Owners")
                        .HasForeignKey("ResidenceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("Packages_service.Models.Packages", b =>
                {
                    b.HasOne("Packages_service.Models.Residence", "Residence")
                        .WithMany("Packages")
                        .HasForeignKey("ResidenceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("Packages_service.Models.Residence", b =>
                {
                    b.Navigation("Owners");

                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
